-- drop statements

-- entity creation statements

CREATE TABLE IF NOT EXISTS user
(
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	username VARCHAR(15) UNIQUE NOT NULL,
	password VARCHAR(25) NOT NULL,
	name VARCHAR(50),
	email VARCHAR(25),
	active BOOLEAN DEFAULT 1 NOT NULL
);

CREATE TABLE IF NOT EXISTS file
(
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	name VARCHAR(50) NOT NULL,
	owner INTEGER NOT NULL,
	writeable BOOLEAN DEFAULT 0 NOT NULL,
	private BOOLEAN DEFAULT 1 NOT NULL,
	created DATETIME DEFAULT CURRENT_TIMESTAMP,
	modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	revision INTEGER UNSIGNED DEFAULT 0,
	description TEXT,
	UNIQUE (name, owner),
	FOREIGN KEY (owner) REFERENCES user(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS bookmark
(
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	title VARCHAR,
	lft INTEGER NOT NULL,
	rgt INTEGER NOT NULL,
	file INTEGER NOT NULL,
	created DATETIME DEFAULT CURRENT_TIMESTAMP,
	modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	revision INTEGER UNSIGNED DEFAULT 0,
--	type ENUM('l','f','s') DEFAULT 'l' NOT NULL,
	UNIQUE (lft, rgt, file),
	FOREIGN KEY (file) REFERENCES file(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS folder
(
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	bookmark INTEGER NOT NULL,
	created DATETIME DEFAULT CURRENT_TIMESTAMP,
	modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	revision INTEGER UNSIGNED DEFAULT 0,
	description TEXT,
	FOREIGN KEY (bookmark) REFERENCES bookmark(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS link
(
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	url VARCHAR UNIQUE NOT NULL,
	keyword VARCHAR,
	bookmark INTEGER NOT NULL,
	created DATETIME DEFAULT CURRENT_TIMESTAMP,
	modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	revision INTEGER UNSIGNED DEFAULT 0,
	description TEXT,
	FOREIGN KEY (bookmark) REFERENCES bookmark(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS tag
(
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	tag VARCHAR,
	created DATETIME DEFAULT CURRENT_TIMESTAMP,
	modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	revision INTEGER UNSIGNED DEFAULT 0
);

CREATE TABLE IF NOT EXISTS linktag
(
	tag INTEGER NOT NULL,
	link INTEGER NOT NULL,
	created DATETIME DEFAULT CURRENT_TIMESTAMP,
	modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	revision INTEGER UNSIGNED DEFAULT 0,
	PRIMARY KEY (tag, link),
	FOREIGN KEY (tag) REFERENCES tag(id) ON DELETE CASCADE,
	FOREIGN KEY (link) REFERENCES link(id) ON DELETE CASCADE
);

