-- drop statements
DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS file;
DROP TABLE IF EXISTS bookmark;
DROP TABLE IF EXISTS folder;
DROP TABLE IF EXISTS link;
DROP TABLE IF EXISTS tag;
DROP TABLE IF EXISTS linktag;
DROP TABLE IF EXISTS fileuser;

-- entity creation statements

CREATE TABLE IF NOT EXISTS user
(
	id INTEGER PRIMARY KEY AUTO_INCREMENT,
	username VARCHAR(15) UNIQUE NOT NULL,
	password VARCHAR(25) NOT NULL,
	name VARCHAR(50),
	email VARCHAR(25),
	active BOOLEAN DEFAULT 1 NOT NULL
);

CREATE TABLE IF NOT EXISTS file
(
	id INTEGER PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(50) NOT NULL,
	owner INTEGER NOT NULL,
--	private BOOLEAN DEFAULT 1 NOT NULL,
	created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	modified TIMESTAMP,
	revision INTEGER UNSIGNED DEFAULT 0,
	description TEXT,
	UNIQUE (name, owner),
	FOREIGN KEY (owner) REFERENCES user(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS bookmark
(
	id INTEGER PRIMARY KEY AUTO_INCREMENT,
	title VARCHAR(255),
	lft INTEGER NOT NULL,
	rgt INTEGER NOT NULL,
	level INTEGER NOT NULL,
	file INTEGER NOT NULL,
	created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	modified TIMESTAMP,
	revision INTEGER UNSIGNED DEFAULT 0,
--	type ENUM('l','f','s') DEFAULT 'l' NOT NULL,
	UNIQUE (lft, rgt, file),
	FOREIGN KEY (file) REFERENCES file(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS folder
(
	id INTEGER PRIMARY KEY AUTO_INCREMENT,
	bookmark INTEGER NOT NULL,
	created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	modified TIMESTAMP,
	revision INTEGER UNSIGNED DEFAULT 0,
	description TEXT,
	FOREIGN KEY (bookmark) REFERENCES bookmark(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS link
(
	id INTEGER PRIMARY KEY AUTO_INCREMENT,
	url VARCHAR(255) UNIQUE NOT NULL,
	keyword VARCHAR(25),
	bookmark INTEGER NOT NULL,
	created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	modified TIMESTAMP,
	revision INTEGER UNSIGNED DEFAULT 0,
	description TEXT,
	FOREIGN KEY (bookmark) REFERENCES bookmark(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS tag
(
	id INTEGER PRIMARY KEY AUTO_INCREMENT,
	tag VARCHAR(50),
	created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	modified TIMESTAMP,
	revision INTEGER UNSIGNED DEFAULT 0
);

CREATE TABLE IF NOT EXISTS linktag
(
	tag INTEGER NOT NULL,
	link INTEGER NOT NULL,
	PRIMARY KEY (tag, link),
	FOREIGN KEY (tag) REFERENCES tag(id) ON DELETE CASCADE,
	FOREIGN KEY (link) REFERENCES link(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS fileuser
(
	file INTEGER NOT NULL,
	user INTEGER NOT NULL,
	modify BOOLEAN DEFAULT 0 NOT NULL,
	PRIMARY KEY (file, user),
	FOREIGN KEY (file) REFERENCES file(id) ON DELETE CASCADE,
	FOREIGN KEY (user) REFERENCES user(id) ON DELETE CASCADE
);

