-- drop statements

--DROP TABLE user;
--DROP TABLE bookmark;
--DROP TABLE folder;
--DROP TABLE file;

--DROP TABLE inside_of;
--DROP TABLE part_of;
--DROP TABLE tag;

-- entity creation statements

CREATE TABLE IF NOT EXISTS user
(
	id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	username VARCHAR(15) UNIQUE NOT NULL,
	password VARCHAR(25) NOT NULL,
	name VARCHAR(50),
	email VARCHAR(25),
	active BOOLEAN DEFAULT 1 NOT NULL
);

CREATE TABLE IF NOT EXISTS bookmark
(
	id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	url VARCHAR(256) NOT NULL,
	title VARCHAR(256),
	icon VARCHAR(256),
	folder INTEGER NOT NULL,
	position INTEGER UNSIGNED DEFAULT 0,
	created DATETIME DEFAULT CURRENT_TIMESTAMP,
--	modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	revision INTEGER UNSIGNED DEFAULT 0,
	keywords VARCHAR(256),
	description TEXT,
	FOREIGN KEY (folder) REFERENCES folder(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS folder
(
	id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	name VARCHAR(50) NOT NULL,
	lft INTEGER NOT NULL,
	rgt INTEGER NOT NULL,
	created DATETIME DEFAULT CURRENT_TIMESTAMP,
--	modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	revision INTEGER UNSIGNED DEFAULT 0,
	description TEXT
);

CREATE TABLE IF NOT EXISTS file
(
	id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	name VARCHAR(50) NOT NULL,
	owner INTEGER NOT NULL,
	writeable BOOLEAN DEFAULT 0 NOT NULL,
	private BOOLEAN DEFAULT 1 NOT NULL,
	created DATETIME DEFAULT CURRENT_TIMESTAMP,
--	modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	revision INTEGER UNSIGNED DEFAULT 0,
	description TEXT,
	UNIQUE (name, owner),
	FOREIGN KEY (owner) REFERENCES user(id) ON DELETE CASCADE
);

-- relationship create statements

CREATE TABLE IF NOT EXISTS part_of
(
	folder INTEGER NOT NULL,
	file INTEGER NOT NULL,
	created DATETIME DEFAULT CURRENT_TIMESTAMP,
	revision INTEGER UNSIGNED DEFAULT 0,
	PRIMARY KEY (folder, file),
	FOREIGN KEY (folder) REFERENCES folder(id),
	FOREIGN KEY (file) REFERENCES file(id)
);

CREATE TABLE IF NOT EXISTS tag
(
	tag VARCHAR(50) NOT NULL,
	file INTEGER NOT NULL,
	bookmark INTEGER NOT NULL,
	created DATETIME DEFAULT CURRENT_TIMESTAMP,
--	modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	revision INTEGER UNSIGNED DEFAULT 0,
	PRIMARY KEY (tag, file, bookmark),
	FOREIGN KEY (file) REFERENCES file(id) ON DELETE CASCADE,
	FOREIGN KEY (bookmark) REFERENCES bookmark(id) ON DELETE CASCADE
);

